version: '2'
# For testing only
services:
  db:
    image: mysql:5.6
    container_name: safehandsdb
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "openmrs"
    volumes:
      - safehands-database:/var/lib/mysql
    restart: unless-stopped 
  refapp:
    depends_on:
      - db
    build: .
    links:
      - db:database
    ports:
      - 8080
    environment:
      DB_HOST: database
      DB_DATABASE: "openmrs"
      DB_USERNAME: "root"
      DB_PASSWORD: "password"
      DB_CREATE_TABLES: "true"
      DB_AUTO_UPDATE: "false"
      MODULE_WEB_ADMIN: "true"
      OPENMRS_ADMIN_PASSWORD: "Safehands@123" # Note: has no effect if DB_CREATE_TABLES set to false
      TZ: "Asia/Kolkata"
    volumes:
      - document-upload:/usr/local/tomcat/.OpenMRS/Document
    restart: unless-stopped

volumes:
  safehands-database:
  document-upload:
 
networks:
 default:
  external:
    name: my-pre-existing-network
